/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.backupsystem.view;

import br.com.backupsystem.controler.ControlerAgenda;
import br.com.backupsystem.model.Agendamento;
import br.com.backupsystem.model.TableModelAgendamento;
import br.com.backupsystem.utils.Utils;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Elias Santana
 */
public class TelaConsulta extends javax.swing.JFrame {

    ControlerAgenda ca = new ControlerAgenda();
    Utils u = new Utils();
    TableModelAgendamento modelAgendamento = new TableModelAgendamento();
    Agendamento agendamento = new Agendamento();
    TelaBackupTray bkpTray;
    String path="C:\\SysBar\\bkp_exec.txt";
    
    public TelaConsulta() {
        initComponents();
        tbAgendamento.setModel(modelAgendamento);
        tbAgendamento.setModel(DbUtils.resultSetToTableModel(ca.listaAgendamento()));
        modelAgendamento.redimensionaColunas(tbAgendamento);
        u.setIcon(this);
        btnAlterarAgendamento.setEnabled(false);
    }

    public void atualizaTabela() {
        tbAgendamento.setModel(DbUtils.resultSetToTableModel(ca.listaAgendamento()));
        modelAgendamento.redimensionaColunas(tbAgendamento);
    }

    public void recebeTela(TelaBackupTray tela){
        this.bkpTray = tela;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAgendamento = new javax.swing.JTable();
        btnAlterarAgendamento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "HORÁRIO", "DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SAB", "BACKUP"
            }
        ));
        tbAgendamento.setRowHeight(21);
        tbAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAgendamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 683, 560));

        btnAlterarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagem/clock.png"))); // NOI18N
        btnAlterarAgendamento.setText("Alterar Agendamento");
        btnAlterarAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarAgendamentoMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagem/stop48x48.png"))); // NOI18N
        jLabel1.setText("Parar Execução");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 150, 50));

        setBounds(298, 0, 724, 671);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAgendamentoMouseClicked
        
        int linha = tbAgendamento.getSelectedRow();

        agendamento.setId(Integer.parseInt(tbAgendamento.getModel().getValueAt(linha, 0).toString()));
        agendamento.setHora(tbAgendamento.getModel().getValueAt(linha, 1).toString());
        agendamento.setDom(retornaValor(tbAgendamento.getModel().getValueAt(linha, 2).toString()));
        agendamento.setSeg(retornaValor(tbAgendamento.getModel().getValueAt(linha, 3).toString()));
        agendamento.setTer(retornaValor(tbAgendamento.getModel().getValueAt(linha, 4).toString()));
        agendamento.setQua(retornaValor(tbAgendamento.getModel().getValueAt(linha, 5).toString()));
        agendamento.setQui(retornaValor(tbAgendamento.getModel().getValueAt(linha, 6).toString()));
        agendamento.setSex(retornaValor(tbAgendamento.getModel().getValueAt(linha, 7).toString()));
        agendamento.setSab(retornaValor(tbAgendamento.getModel().getValueAt(linha, 8).toString()));
        
        String tipo = tbAgendamento.getModel().getValueAt(linha, 9).toString();
       
        switch (tipo.toLowerCase()) {
            case "total":
                agendamento.setTipo(Agendamento.Tipo.TOTAL);
            break;
            case "diferecial":
                agendamento.setTipo(Agendamento.Tipo.DIFERENCIAL);
            break;
            case "incremental":
                agendamento.setTipo(Agendamento.Tipo.INCREMENTAL);
            break;

        }
        btnAlterarAgendamento.setEnabled(true);
       

    }//GEN-LAST:event_tbAgendamentoMouseClicked

    private void btnAlterarAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarAgendamentoMouseClicked
       TelaAlterarAgendamento alteraAgendamento = new TelaAlterarAgendamento();
       alteraAgendamento.setTitle("BackupSystem - Alteração de Agendamento");
       alteraAgendamento.recebeAgendamento(this,agendamento);
       alteraAgendamento.recebeTela(bkpTray);
       alteraAgendamento.setVisible(true);
    }//GEN-LAST:event_btnAlterarAgendamentoMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        u.deletaArquivo(path);
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
        
    }//GEN-LAST:event_formWindowClosed
    private int retornaValor(String valor) {
        int set = 0;
        if (!"-".equals(valor)) {
            set = 1;
        }

        return set;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAlterarAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAgendamento;
    // End of variables declaration//GEN-END:variables
}
