/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.backupsystem.view;

import br.com.backupsystem.controler.ControlerAgenda;
import br.com.backupsystem.model.Agendamento;
import br.com.backupsystem.utils.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias Santana
 */
public class TelaAgenda extends javax.swing.JFrame {

    ControlerAgenda ca = new ControlerAgenda();
    TelaBackupTray bkpTray;
    Utils u = new Utils();
    TelaConsulta tc = new TelaConsulta();

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        u.setIcon(this);
    }

    public void recebeTela(TelaBackupTray tela) {
        bkpTray = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelDias = new javax.swing.JPanel();
        jcheckSeg = new javax.swing.JCheckBox();
        jcheckTer = new javax.swing.JCheckBox();
        jcheckQua = new javax.swing.JCheckBox();
        jcheckQui = new javax.swing.JCheckBox();
        jcheckSex = new javax.swing.JCheckBox();
        jcheckSab = new javax.swing.JCheckBox();
        jcheckDom = new javax.swing.JCheckBox();
        comboHorario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        btnAgendar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDias.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dias")));

        buttonGroup1.add(jcheckSeg);
        jcheckSeg.setText("Segundas");

        buttonGroup1.add(jcheckTer);
        jcheckTer.setText("Terças");
        jcheckTer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckTerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jcheckQua);
        jcheckQua.setText("Quartas");

        buttonGroup1.add(jcheckQui);
        jcheckQui.setText("Quintas");

        buttonGroup1.add(jcheckSex);
        jcheckSex.setText("Sextas");

        buttonGroup1.add(jcheckSab);
        jcheckSab.setText("Sábados");

        buttonGroup1.add(jcheckDom);
        jcheckDom.setText("Domingo");

        javax.swing.GroupLayout panelDiasLayout = new javax.swing.GroupLayout(panelDias);
        panelDias.setLayout(panelDiasLayout);
        panelDiasLayout.setHorizontalGroup(
            panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcheckSab)
                    .addComponent(jcheckDom)
                    .addComponent(jcheckSeg)
                    .addComponent(jcheckTer)
                    .addComponent(jcheckQua)
                    .addComponent(jcheckQui)
                    .addComponent(jcheckSex))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelDiasLayout.setVerticalGroup(
            panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jcheckDom)
                .addGap(3, 3, 3)
                .addComponent(jcheckSeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckTer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckQua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckQui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckSex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckSab)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(panelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 237));

        comboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "00:00:00", "01:00:00", "02:00:00", "03:00:00", "04:00:00", "05:00:00", "06:00:00", "07:00:00", "08:00:00", "09:00:00", "10:00:00", "11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00", "22:00:00", "23:00:00" }));
        getContentPane().add(comboHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 27, 125, 30));

        jLabel1.setText("Horário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 11, -1, -1));

        jLabel2.setText("Tipo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 63, 56, 21));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Total", "Incremental", "Diferencial" }));
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 86, 125, 30));

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 177, 125, 32));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 132, 125, 32));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 216, 125, 32));

        setBounds(0, 0, 305, 298);
    }// </editor-fold>//GEN-END:initComponents

    private void jcheckTerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckTerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckTerActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Sair do Bakup!", "Atenção", JOptionPane.ERROR_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        Agendamento a = new Agendamento();
        a.setDom(0);
        a.setSeg(0);
        a.setTer(0);
        a.setQua(0);
        a.setQui(0);
        a.setSex(0);
        a.setSab(0);

        String tipo = comboTipo.getSelectedItem().toString();
        switch (tipo) {
            case "Total":
                a.setTipo(Agendamento.Tipo.TOTAL);
                break;
            case "Diferencial":
                a.setTipo(Agendamento.Tipo.DIFERENCIAL);
                break;
            case "Incremental":
                a.setTipo(Agendamento.Tipo.INCREMENTAL);
                break;

        }
        a.setHora(comboHorario.getSelectedItem().toString());

        if (jcheckDom.isSelected()) {
            a.setDom(1);
        }
        if (jcheckSeg.isSelected()) {
            a.setSeg(1);
        }
        if (jcheckTer.isSelected()) {
            a.setTer(1);
        }
        if (jcheckQua.isSelected()) {
            a.setQua(1);
        }
        if (jcheckQui.isSelected()) {
            a.setQui(1);
        }
        if (jcheckSex.isSelected()) {
            a.setSex(1);
        }
        if (jcheckSab.isSelected()) {
            a.setSab(1);
        }

        String diaDaSemana = null;
        if (jcheckDom.isSelected()) {
            diaDaSemana = "dom";
        }
        if (jcheckSeg.isSelected()) {
            diaDaSemana = "seg";
        }
        if (jcheckTer.isSelected()) {
            diaDaSemana = "ter";
        }
        if (jcheckQua.isSelected()) {
            diaDaSemana = "qua";
        }
        if (jcheckQui.isSelected()) {
            diaDaSemana = "qui";
        }
        if (jcheckSab.isSelected()) {
            diaDaSemana = "sex";
        }

        int idHora = ca.retornaIdHorario(comboHorario.getSelectedItem().toString());
        System.out.println("Id Horário: " + idHora);
        System.out.println("Dia da Semana: " + diaDaSemana);

        if (ca.temAgendamento(diaDaSemana, comboHorario.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Já existe agendamento para o dia e horário informado!");
        } else {
            if (idHora == 0) {
                // Adiciona Registro
                ca.adicionaAgendamento(a);
            } else {

                System.out.println(ca.alteraAgendamento(diaDaSemana, String.valueOf(idHora)));
            }
            JOptionPane.showMessageDialog(this, "Agendamento Realizado com sucesso!");
            tc.atualizaTabela();
            limpaCheckBox();
        }

    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        tc.setTitle("Backup - Consultar Agendamentos");
        tc.setVisible(true);


    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboHorario;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jcheckDom;
    private javax.swing.JCheckBox jcheckQua;
    private javax.swing.JCheckBox jcheckQui;
    private javax.swing.JCheckBox jcheckSab;
    private javax.swing.JCheckBox jcheckSeg;
    private javax.swing.JCheckBox jcheckSex;
    private javax.swing.JCheckBox jcheckTer;
    private javax.swing.JPanel panelDias;
    // End of variables declaration//GEN-END:variables

    private void limpaCheckBox() {
        jcheckDom.setSelected(false);
        jcheckSeg.setSelected(false);
        jcheckTer.setSelected(false);
        jcheckQua.setSelected(false);
        jcheckQui.setSelected(false);
        jcheckSex.setSelected(false);
        jcheckSab.setSelected(false);
    }

}
